apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      valueFrom: 
        configMapKeyRef:
          name: pod-config # name of the configmap you are refering to
          key: course # env.name and config map key name can be different
    - name: duration
      valueFrom:
        configMapKeyRef:
          name: pod-config
          key: duration
