apiVersion: v1
kind: Pod
metadata:
  name: env-configmap
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: pod-config
        key: DURATION




    # env:
    # - name: course
    #   valueFrom: 
    #     configMapKeyRef:
    #       name: pod-config   # name of the configmap you are refering to
    #       key: COURSE        # env.name and config map key name can be different
    # - name: duration
    #   valueFrom:
    #     configMapKeyRef:
    #       name: pod-config
    #       key: DURATION
