apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels: #replicaset labels
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 30
  selector:
  # these labels are used to select the pod to create replicas
    matchLabels:
      tier: frontend
      app: nginx
  #this is pod definition
  template:
    metadata:
    # these labels belongs to pod
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:trixie-perl

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    purpose: service-demo
spec:
  selector:
    tier: frontend
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
